#!/bin/bash
BASEDIR=$(dirname $0)
source $BASEDIR/venv/bin/activate
rm $BASEDIR/db.sqlite3

python $BASEDIR/manage.py makemigrations
python $BASEDIR/manage.py migrate

chown za:www-data $BASEDIR/db.sqlite3
chmod 775 $BASEDIR/db.sqlite3
